slices:
  - sources:
      - model: PLACEHOLDER
        layer_range: [0, 32]
      - model: meta-llama/Llama-2-7b-hf
        layer_range: [0, 32]

merge_method: slerp
base_model: PLACEHOLDER
merge_name: slerp-0.7

parameters:
  t:
    - value: 0.7 # fallback for rest of tensors
tokenizer_source: union

dtype: bfloat16
