name: main
n_samples: 100
prompt_length: 50
min_token_length: 200
max_token_length: 200
dataset_config:
  path: "allenai/c4"
  name: "realnewslike"
  split: "validation"
  data_field: "text"
batch_size: 16
compute_ppl: true
ppl_model: "meta-llama/Llama-3.1-8B-Instruct"
