base_model: PLACEHOLDER
dtype: float32
training_args:
  overwrite_output_dir: true
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 2
  gradient_checkpointing: false
  learning_rate: 0.00001
  num_train_epochs: 1
  do_train: true
  max_steps: 2500
  optim: adafactor 
  lr_scheduler_type: cosine
  warmup_ratio : 0.1
  save_strategy: steps
  save_steps: 500
  bf16: false
  fp16: false
  logging_steps : 100
  push_to_hub: false
train_dataset: learnability_adv