# Config from: https://huggingface.co/sethuiyer/Dr_Samantha-7b
slices:
  - sources:
      - model: Severus27/BeingWell_llama2_7b
        layer_range: [0, 32]
      - model: PLACEHOLDER
        layer_range: [0, 32]

merge_method: slerp
base_model: PLACEHOLDER
merge_name: Dr_Samantha-7b

parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5 # fallback for rest of tensors
tokenizer_source: union

dtype: bfloat16
